Attribute VB_Name = "Module1"
Public Answer As String
Public Wrongs As Integer
Public TotPrize As String
Public QuestionNum As Integer
Public LabelAnswer As String
Public OldQuest1 As Integer
Public OldQuest2 As Integer
Public OldQuest3 As Integer
Public OldQuest4 As Integer
Public OldQuest5 As Integer
Public OldQuest6 As Integer
Public OldQuest7 As Integer
Public OldQuest8 As Integer
Public OldQuest9 As Integer
Public OldQuest10 As Integer
Public OldQuest11 As Integer
Public OldQuest12 As Integer
Public OldQuest13 As Integer
Public OldQuest14 As Integer
Public OldQuest15 As Integer
Public Starts As Integer
Public RightAns As Integer

